FROM kalilinux/kali-rolling:latest
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      nmap \
      netcat-openbsd \
      curl \
      dnsutils \
      iproute2 \
      tcpdump \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV TERM=xterm-256color
ENTRYPOINT ["/bin/bash", "-lc"]
